
CC = gcc
SRC = hello.c
TARGET = hello

$(TARGET): $(SRC)
	$(CC) $(SRC) -o $(TARGET)

ball: ball.c
	gcc ball.c -o ball -lpthread

world: world.c
	gcc world.c -o world

racing: racing.c
	gcc racing.c -o racing -lpthread

