# Generated by Django 3.2.16 on 2023-01-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_reply_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='polls.question'),
        ),
    ]
