# Generated by Django 3.2.16 on 2023-01-18 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_alter_reply_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='vote_users',
            field=models.ManyToManyField(related_name='vote_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
