# Generated by Django 3.2.16 on 2023-01-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20230117_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='likes',
        ),
        migrations.AddField(
            model_name='feed',
            name='like_people',
            field=models.ManyToManyField(related_name='like_feeds', to='facebook.Person'),
        ),
    ]
