# Generated by Django 3.2.16 on 2023-01-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openDt', models.CharField(max_length=30)),
                ('showTime', models.CharField(max_length=100)),
            ],
        ),
    ]
