# Generated by Django 3.2.16 on 2023-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_passwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user_name', models.CharField(max_length=10)),
                ('user_gender', models.IntegerField(choices=[(1, 'FEMALE'), (2, 'MALE')], max_length=1)),
                ('phone_num', models.CharField(max_length=8)),
                ('user_age', models.IntegerField(max_length=100)),
            ],
        ),
    ]
